# We expect runtime error because we have _ in the end

x = 1_000_1_1_
see type(x)